Lesson7 1
mhope21/R7-forum pull request #2
Opened 2024-07-29 17:58 UTC by mhope21

This is lesson 7

2024-08-05 18:15 UTC, raquii commented
I am not sure how, but your model, migrations, and controllers are missing from this PR, and I am realizing now that they were also missing from lesson 6, but I _saw them_ when we met for our 1:1. Are you not including those in your commits? 🤔

2024-08-24 23:03 UTC, dsinn requested changes
All of the code looks good, so well done! However, I'd just like to see revised answers for questions 6 and 7 (see other comments).

2024-08-24 23:03 UTC, dsinn commented on lesson7-questions.txt
> +belongs to a user and Rails associates the new subcription with that specific user.
This answers the second part of the question. The first part is:

> What kind of object is returned by user.subscriptions?

Could you provide the answer?

2024-08-24 23:03 UTC, dsinn commented on lesson7-questions.txt
> +  WHERE "subscriptions"."user_id" = ?  [["user_id", 1]]
The first part of question asks for the Active Record statement, but this is only SQL. The SQL also returns forum records joined with subscriptions, while the question is asking for post records. Could you revise the SQL statement and provide the Active Record statement?

2024-08-24 23:03 UTC, dsinn commented on lesson7-questions.txt
> +Any idea why one says destroy and one says delete, even though I have no method called delete?
This was a mistake in the starter code. In idiomatic Rails, `destroy` is the correct method to define.

2024-08-24 23:03 UTC, dsinn commented on lesson7-questions.txt
> +It also sets the post on destroy to make sure you are deleting the right one, correct?
Correct.

2024-08-24 23:03 UTC, dsinn commented on lesson7-questions.txt
> +will include the forum_id, but the show, edit, update,and destroy will not because of the shallow: true?
Yes, the `shallow` option is "smart" about which CRUD operations require a forum_id and which ones don't (there's an example on [their docs](https://guides.rubyonrails.org/routing.html#shallow-nesting)).

2024-08-24 23:03 UTC, dsinn commented on lesson7-questions.txt
> +The index route is unaffected by the nesting because of except: [:index]? This is the relevant code, I believe:
Correct, the `except` excludes the actions in the array from being created under the nesting.

2024-08-25 14:31 UTC, mhope21 commented on lesson7-questions.txt
> +belongs to a user and Rails associates the new subcription with that specific user.
Is the answer not that a new subscription object is created? Or are you looking for something different?

2024-08-25 15:25 UTC, mhope21 commented on lesson7-questions.txt
> +belongs to a user and Rails associates the new subcription with that specific user.
I see my mistake now. I was only focused on the second part of the question where it asked about user.subscriptions.new. I will answer the first part of the question.

2024-08-25 17:48 UTC, dsinn approved these changes

2024-08-25 17:48 UTC, dsinn commented on lesson7-questions.txt
> +user_posts_in_forum = Post.where(user_id: user.id, forum_id: forum.id)
This works. An alternative solution could make use of the association methods, like so:

```ruby
user.posts.where(forum: forum)
```

2024-08-25 23:31 UTC, merged